import type { Theme } from '../types'

export const defaultTheme: Theme = {
  id: 'default',
  name: '极简灰',
  description: '简洁清爽，适合日常排版',
  styles: {
    container: {
      width: '100%',
      padding: '0',
      fontFamily: '-apple-system, "PingFang SC", "Microsoft YaHei", sans-serif',
      color: '#3f3f3f',
      lineHeight: '1.75',
      fontSize: '15px',
    },
    p: { margin: '1em 0', letterSpacing: '0.05em' },
    h1: {
      fontSize: '24px',
      fontWeight: '700',
      color: '#000',
      textAlign: 'center',
      margin: '1.5em 0 1em',
    },
    h2: {
      fontSize: '20px',
      fontWeight: '700',
      color: '#000',
      borderLeft: '4px solid #5e72e4',
      paddingLeft: '12px',
      margin: '1.2em 0 0.6em',
    },
    h3: {
      fontSize: '17px',
      fontWeight: '700',
      color: '#5e72e4',
      margin: '1.2em 0 0.6em',
    },
    h4: { fontSize: '15px', fontWeight: '700', color: '#3f3f3f' },
    strong: { color: '#5e72e4', fontWeight: '700' },
    em: { fontStyle: 'italic' },
    u: { textDecoration: 'underline' },
    s: { textDecoration: 'line-through' },
    a: { color: '#5e72e4', textDecoration: 'none' },
    ul: { paddingLeft: '24px', margin: '1em 0', listStyleType: 'disc' },
    ol: { paddingLeft: '24px', margin: '1em 0', listStyleType: 'decimal' },
    li: { margin: '0.4em 0' },
    blockquote: {
      borderLeft: '3px solid #5e72e4',
      padding: '8px 16px',
      background: '#f7f8fc',
      color: '#666',
      margin: '1em 0',
    },
    code: {
      background: '#f4f5f7',
      color: '#e83e8c',
      padding: '2px 6px',
      borderRadius: '3px',
      fontSize: '0.9em',
      fontFamily: '"SF Mono", Consolas, Monaco, monospace',
    },
    pre: {
      background: '#1e1e1e',
      color: '#d4d4d4',
      padding: '16px 20px',
      borderRadius: '6px',
      overflowX: 'auto',
      lineHeight: '1.5',
      fontSize: '13px',
      margin: '1em 0',
    },
    preCode: {
      background: 'transparent',
      color: 'inherit',
      padding: '0',
      borderRadius: '0',
      fontSize: 'inherit',
    },
    hr: { border: '0', height: '1px', background: '#e5e7eb', margin: '2em 0' },
    img: { maxWidth: '100%', borderRadius: '4px', display: 'block', margin: '1em auto' },
    table: {
      borderCollapse: 'collapse',
      width: '100%',
      fontSize: '14px',
      margin: '1em 0',
    },
    th: {
      background: '#f7f8fc',
      fontWeight: '700',
      padding: '8px 12px',
      border: '1px solid #e5e7eb',
    },
    td: { padding: '8px 12px', border: '1px solid #e5e7eb' },
    taskList: { listStyleType: 'none', paddingLeft: '0' },
    taskItem: { display: 'flex', alignItems: 'flex-start', gap: '6px' },
  },
}
