import type { Theme } from '../types'

export const elegantTheme: Theme = {
  id: 'elegant',
  name: '文艺范',
  description: '衬线字体，米白底色，书卷气息',
  styles: {
    container: {
      width: '100%',
      padding: '0',
      fontFamily: '"Songti SC", "Source Han Serif", Georgia, serif',
      color: '#5a4634',
      lineHeight: '1.85',
      fontSize: '16px',
      background: '#fdfaf3',
    },
    p: { margin: '1em 0' },
    h1: {
      fontSize: '26px',
      color: '#3a2e1f',
      textAlign: 'center',
      borderBottom: '2px solid #d4a574',
      paddingBottom: '12px',
      margin: '1.5em 0 1em',
      fontWeight: '700',
    },
    h2: {
      fontSize: '21px',
      color: '#8b6914',
      borderLeft: '4px solid #d4a574',
      paddingLeft: '14px',
      fontWeight: '700',
      margin: '1.2em 0 0.6em',
    },
    h3: { fontSize: '17px', color: '#8b6914', fontStyle: 'italic', fontWeight: '600' },
    h4: { fontSize: '15px', fontWeight: '600', color: '#5a4634' },
    strong: { color: '#c9302c', fontWeight: '700' },
    em: { fontStyle: 'italic' },
    u: { textDecoration: 'underline' },
    s: { textDecoration: 'line-through' },
    a: { color: '#8b6914', textDecoration: 'underline' },
    ul: { paddingLeft: '24px', margin: '1em 0', listStyleType: 'disc' },
    ol: { paddingLeft: '24px', margin: '1em 0', listStyleType: 'decimal' },
    li: { margin: '0.4em 0' },
    blockquote: {
      borderLeft: '4px solid #d4a574',
      background: '#faf3e0',
      padding: '12px 18px',
      color: '#7a5c2e',
      fontStyle: 'italic',
      margin: '1em 0',
    },
    code: {
      background: '#f4ede0',
      color: '#a0522d',
      padding: '2px 6px',
      borderRadius: '3px',
      fontSize: '0.9em',
      fontFamily: '"SF Mono", Consolas, Monaco, monospace',
    },
    pre: {
      background: '#3a2e1f',
      color: '#f4ede0',
      padding: '16px 20px',
      borderRadius: '6px',
      overflowX: 'auto',
      lineHeight: '1.5',
      fontSize: '13px',
      margin: '1em 0',
    },
    preCode: {
      background: 'transparent',
      color: 'inherit',
      padding: '0',
      borderRadius: '0',
      fontSize: 'inherit',
    },
    hr: {
      border: '0',
      height: '1px',
      width: '60%',
      margin: '2em auto',
      background: '#d4a574',
    },
    img: {
      maxWidth: '100%',
      borderRadius: '8px',
      boxShadow: '0 4px 12px rgba(0,0,0,0.08)',
      display: 'block',
      margin: '1em auto',
    },
    table: {
      borderCollapse: 'collapse',
      width: '100%',
      fontSize: '14px',
      margin: '1em 0',
    },
    th: {
      background: '#faf3e0',
      fontWeight: '700',
      padding: '8px 12px',
      border: '1px solid #d4a574',
      color: '#5a4634',
    },
    td: { padding: '8px 12px', border: '1px solid #d4a574' },
    taskList: { listStyleType: 'none', paddingLeft: '0' },
    taskItem: { display: 'flex', alignItems: 'flex-start', gap: '6px' },
  },
}
