import type { Theme } from '../types'

export const techTheme: Theme = {
  id: 'tech',
  name: '极客风',
  description: '等宽字体，蓝紫强调，代码感',
  styles: {
    container: {
      width: '100%',
      padding: '0',
      fontFamily: '"JetBrains Mono", "PingFang SC", monospace',
      color: '#1a1a2e',
      lineHeight: '1.7',
      fontSize: '15px',
    },
    p: { margin: '1em 0' },
    h1: {
      fontSize: '24px',
      color: '#0f3460',
      borderBottom: '3px double #0f3460',
      paddingBottom: '8px',
      fontWeight: '700',
      margin: '1.5em 0 1em',
    },
    h2: {
      fontSize: '20px',
      color: '#ffffff',
      background: 'linear-gradient(90deg, #e94560 0%, transparent 100%)',
      padding: '8px 12px',
      fontWeight: '700',
      margin: '1.2em 0 0.6em',
      borderRadius: '4px',
    },
    h3: {
      fontSize: '17px',
      color: '#e94560',
      borderLeft: '4px solid #e94560',
      paddingLeft: '10px',
      fontWeight: '600',
      margin: '1.2em 0 0.6em',
    },
    h4: { fontSize: '15px', fontWeight: '600', color: '#1a1a2e' },
    strong: { color: '#e94560', fontWeight: '700' },
    em: { fontStyle: 'italic' },
    u: { textDecoration: 'underline' },
    s: { textDecoration: 'line-through' },
    a: { color: '#0f3460', textDecoration: 'underline wavy' },
    ul: { paddingLeft: '24px', margin: '1em 0', listStyleType: 'disc' },
    ol: { paddingLeft: '24px', margin: '1em 0', listStyleType: 'decimal' },
    li: { margin: '0.4em 0' },
    blockquote: {
      borderLeft: '4px solid #e94560',
      background: '#f5f5f7',
      padding: '8px 16px',
      color: '#16213e',
      margin: '1em 0',
    },
    code: {
      background: '#0f3460',
      color: '#e94560',
      padding: '2px 8px',
      borderRadius: '4px',
      fontSize: '0.9em',
      fontFamily: '"JetBrains Mono", monospace',
    },
    pre: {
      background: '#0f1419',
      color: '#e8e8e8',
      padding: '16px 20px',
      borderRadius: '6px',
      overflowX: 'auto',
      lineHeight: '1.5',
      fontSize: '13px',
      margin: '1em 0',
      borderLeft: '4px solid #e94560',
      fontFamily: '"JetBrains Mono", monospace',
    },
    preCode: {
      background: 'transparent',
      color: 'inherit',
      padding: '0',
      borderRadius: '0',
      fontSize: 'inherit',
    },
    hr: {
      border: '0',
      height: '2px',
      background: 'linear-gradient(90deg, transparent, #0f3460, transparent)',
      margin: '2em 0',
    },
    img: { maxWidth: '100%', borderRadius: '4px', display: 'block', margin: '1em auto' },
    table: {
      borderCollapse: 'collapse',
      width: '100%',
      fontSize: '14px',
      margin: '1em 0',
    },
    th: {
      background: '#f5f5f7',
      fontWeight: '700',
      padding: '8px 12px',
      border: '1px solid #e5e7eb',
      color: '#1a1a2e',
    },
    td: { padding: '8px 12px', border: '1px solid #e5e7eb' },
    taskList: { listStyleType: 'none', paddingLeft: '0' },
    taskItem: { display: 'flex', alignItems: 'flex-start', gap: '6px' },
  },
}
