import type { Industry, IndustryId, ContentTypeId } from './types';

export const industries: Industry[] = [
  {
    id: 'tech',
    name: '科技互联网',
    icon: 'Cpu',
    color: '#2563EB',
    description: '极简、未来感、数据驱动',
    recommendedTypes: ['productLaunch', 'dataReport', 'deepFeature', 'newsReport'],
    recommendedLayouts: ['basic-hero', 'basic-feature-grid', 'basic-data-dashboard', 'poster-data'],
    keywords: ['科技创新', '数字化转型', '人工智能', '云计算', 'SaaS', '互联网产品'],
  },
  {
    id: 'finance',
    name: '金融财经',
    icon: 'TrendingUp',
    color: '#D97706',
    description: '专业、稳重、权威',
    recommendedTypes: ['dataReport', 'deepFeature', 'newsReport', 'yearReview'],
    recommendedLayouts: ['basic-data-dashboard', 'poster-data', 'basic-magazine', 'basic-timeline'],
    keywords: ['金融市场', '投资理财', '宏观经济', '行业分析', '财富管理', '风险控制'],
  },
  {
    id: 'medical',
    name: '医疗健康',
    icon: 'Heart',
    color: '#059669',
    description: '温暖、可信、科学',
    recommendedTypes: ['tutorial', 'deepFeature', 'brandStory', 'newsReport'],
    recommendedLayouts: ['basic-steps', 'basic-quote-flow', 'creative-info-long', 'basic-hero'],
    keywords: ['健康科普', '医疗技术', '养生保健', '心理健康', '临床研究', '公共卫生'],
  },
  {
    id: 'education',
    name: '教育培训',
    icon: 'GraduationCap',
    color: '#7C3AED',
    description: '活力、知识、成长',
    recommendedTypes: ['tutorial', 'activityPromo', 'brandStory', 'interview'],
    recommendedLayouts: ['basic-steps', 'basic-cta', 'basic-quote-flow', 'poster-people'],
    keywords: ['在线教育', '学习方法', '知识付费', '职业发展', '技能培训', '终身学习'],
  },
  {
    id: 'food',
    name: '餐饮美食',
    icon: 'UtensilsCrossed',
    color: '#DC2626',
    description: '食欲、温暖、烟火气',
    recommendedTypes: ['productLaunch', 'brandStory', 'activityPromo', 'tutorial'],
    recommendedLayouts: ['poster-product', 'basic-hero', 'basic-magazine', 'creative-journal'],
    keywords: ['美食探店', '新品上市', '烹饪教程', '食材推荐', '餐饮品牌', '味觉体验'],
  },
  {
    id: 'travel',
    name: '旅游出行',
    icon: 'Plane',
    color: '#0891B2',
    description: '自由、清新、探索',
    recommendedTypes: ['brandStory', 'tutorial', 'activityPromo', 'deepFeature'],
    recommendedLayouts: ['basic-hero', 'basic-magazine', 'creative-journal', 'basic-timeline'],
    keywords: ['旅行攻略', '目的地推荐', '民宿体验', '自驾游', '文化旅行', '户外探险'],
  },
  {
    id: 'ecommerce',
    name: '电商零售',
    icon: 'ShoppingBag',
    color: '#EA580C',
    description: '促销、紧迫、活力',
    recommendedTypes: ['activityPromo', 'productLaunch', 'dataReport', 'yearReview'],
    recommendedLayouts: ['basic-cta', 'poster-product', 'basic-data-dashboard', 'poster-activity'],
    keywords: ['促销活动', '新品首发', '直播带货', '用户增长', '供应链', '消费趋势'],
  },
  {
    id: 'realestate',
    name: '房产家居',
    icon: 'Home',
    color: '#A16207',
    description: '品质、空间、生活',
    recommendedTypes: ['productLaunch', 'brandStory', 'deepFeature', 'activityPromo'],
    recommendedLayouts: ['basic-hero', 'basic-magazine', 'poster-product', 'basic-feature-grid'],
    keywords: ['楼盘推介', '家居设计', '装修指南', '房产投资', '生活美学', '空间改造'],
  },
  {
    id: 'auto',
    name: '汽车出行',
    icon: 'Car',
    color: '#334155',
    description: '工业、精密、速度',
    recommendedTypes: ['productLaunch', 'deepFeature', 'dataReport', 'interview'],
    recommendedLayouts: ['basic-hero', 'basic-feature-grid', 'basic-data-dashboard', 'poster-people'],
    keywords: ['新车发布', '智能驾驶', '新能源汽车', '汽车测评', '出行方式', '车联网'],
  },
  {
    id: 'baby',
    name: '母婴育儿',
    icon: 'Baby',
    color: '#EC4899',
    description: '温馨、可爱、安心',
    recommendedTypes: ['tutorial', 'brandStory', 'productLaunch', 'interview'],
    recommendedLayouts: ['creative-journal', 'basic-steps', 'basic-quote-flow', 'basic-hero'],
    keywords: ['育儿经验', '母婴产品', '亲子教育', '儿童健康', '成长记录', '早教启蒙'],
  },
  {
    id: 'fitness',
    name: '运动健身',
    icon: 'Dumbbell',
    color: '#16A34A',
    description: '动感、力量、健康',
    recommendedTypes: ['tutorial', 'activityPromo', 'brandStory', 'dataReport'],
    recommendedLayouts: ['basic-steps', 'basic-cta', 'basic-hero', 'poster-activity'],
    keywords: ['健身计划', '运动营养', '赛事报道', '训练方法', '运动装备', '健康生活'],
  },
  {
    id: 'workplace',
    name: '职场办公',
    icon: 'Briefcase',
    color: '#475569',
    description: '高效、专业、干练',
    recommendedTypes: ['tutorial', 'deepFeature', 'interview', 'yearReview'],
    recommendedLayouts: ['basic-steps', 'basic-timeline', 'basic-quote-flow', 'creative-info-long'],
    keywords: ['职场技能', '管理方法', '办公效率', '求职面试', '团队建设', '职业规划'],
  },
  {
    id: 'legal',
    name: '法律咨询',
    icon: 'Scale',
    color: '#1E40AF',
    description: '公正、严谨、权威',
    recommendedTypes: ['tutorial', 'deepFeature', 'newsReport', 'interview'],
    recommendedLayouts: ['basic-steps', 'creative-dialogue', 'basic-quote-flow', 'basic-magazine'],
    keywords: ['法律科普', '案例分析', '法规解读', '合同知识', '知识产权', '劳动权益'],
  },
  {
    id: 'culture',
    name: '文化艺术',
    icon: 'Palette',
    color: '#9333EA',
    description: '文艺、审美、格政',
    recommendedTypes: ['brandStory', 'deepFeature', 'interview', 'activityPromo'],
    recommendedLayouts: ['creative-magazine-cover', 'basic-quote-flow', 'basic-hero', 'creative-journal'],
    keywords: ['艺术展览', '文化传承', '创意设计', '美学生活', '文创产品', '艺术评论'],
  },
  {
    id: 'beauty',
    name: '美妆护肤',
    icon: 'Sparkles',
    color: '#DB2777',
    description: '精致、时尚、种草',
    recommendedTypes: ['productLaunch', 'tutorial', 'interview', 'brandStory'],
    recommendedLayouts: ['poster-people', 'basic-steps', 'poster-product', 'creative-journal'],
    keywords: ['产品测评', '护肤知识', '美妆教程', '成分科普', '品牌故事', '时尚趋势'],
  },
  {
    id: 'government',
    name: '政务公益',
    icon: 'Building2',
    color: '#B91C1C',
    description: '正式、庄重、可信',
    recommendedTypes: ['newsReport', 'boardReport', 'activityPromo', 'dataReport'],
    recommendedLayouts: ['board-multi-headline', 'basic-data-dashboard', 'board-festival', 'basic-timeline'],
    keywords: ['政策解读', '政务公开', '公益活动', '民生服务', '城市发展', '社会治理'],
  },
];

/** 根据 ID 获取行业 */
export function getIndustry(id: IndustryId): Industry | undefined {
  return industries.find(i => i.id === id);
}

/** 获取推荐内容类型 */
export function getRecommendedTypes(industryId: IndustryId): ContentTypeId[] {
  return getIndustry(industryId)?.recommendedTypes ?? [];
}
