import type { Material } from '../../types';

export const DECORATION_DIVIDERS: Material[] = [
  { id: 'divider-deco-wave', kind: 'divider', category: 'divider-decoration',
    name: '波浪', keywords: ['波浪'],
    thumbnail: '<div style="text-align:center;color:#999;">～～～</div>',
    html: '<section style="text-align:center;color:#9ca3af;font-size:18px;letter-spacing:0.3em;margin:2em 0;line-height:1;">～～～～～</section>' },
  { id: 'divider-deco-double-thin', kind: 'divider', category: 'divider-decoration',
    name: '细双线', keywords: ['双线'],
    thumbnail: '<div><div style="border-top:1px solid #999;"></div><div style="border-top:1px solid #999;margin-top:3px;"></div></div>',
    html: '<section style="margin:2em 0;"><div style="border-top:1px solid #d1d5db;"></div><div style="border-top:1px solid #d1d5db;margin-top:4px;"></div></section>' },
  { id: 'divider-deco-line-dot', kind: 'divider', category: 'divider-decoration',
    name: '带圆点横线', keywords: ['圆点', '横线'],
    thumbnail: '<div style="display:flex;align-items:center;justify-content:center;"><div style="flex:1;border-top:1px solid #999;"></div><div style="width:6px;height:6px;background:#999;border-radius:50%;margin:0 8px;"></div><div style="flex:1;border-top:1px solid #999;"></div></div>',
    html: '<section style="display:flex;align-items:center;justify-content:center;margin:2em 0;"><div style="flex:1;border-top:1px solid #9ca3af;"></div><div style="width:8px;height:8px;background:#9ca3af;border-radius:50%;margin:0 12px;"></div><div style="flex:1;border-top:1px solid #9ca3af;"></div></section>' },
  { id: 'divider-deco-up-down', kind: 'divider', category: 'divider-decoration',
    name: '上下细线', keywords: ['上下', '细线'],
    thumbnail: '<div style="height:6px;border-top:1px solid #999;border-bottom:1px solid #999;"></div>',
    html: '<section style="height:8px;border-top:1px solid #9ca3af;border-bottom:1px solid #9ca3af;margin:2em 0;"></section>' },
  { id: 'divider-deco-zigzag', kind: 'divider', category: 'divider-decoration',
    name: '锯齿状', keywords: ['锯齿'],
    thumbnail: '<div style="text-align:center;color:#999;letter-spacing:-2px;">∧∧∧</div>',
    html: '<section style="text-align:center;color:#9ca3af;font-size:14px;letter-spacing:-2px;margin:2em 0;line-height:1;">∧∧∧∧∧∧∧∧∧∧∧</section>' },
  // ── 新增装饰 ──
  { id: 'divider-deco-stars-line', kind: 'divider', category: 'divider-decoration',
    name: '星星横线', keywords: ['星星', '横线', '闪烁'],
    thumbnail: '<div style="display:flex;align-items:center;justify-content:center;gap:8px;"><div style="flex:1;border-top:1px solid #ddd;"></div><div style="color:#fbbf24;">★</div><div style="flex:1;border-top:1px solid #ddd;"></div></div>',
    html: '<section style="display:flex;align-items:center;justify-content:center;margin:2em 0;"><div style="flex:1;border-top:1px solid #e5e7eb;"></div><section style="padding:0 16px;color:#fbbf24;font-size:14px;">★ ★ ★</section><div style="flex:1;border-top:1px solid #e5e7eb;"></div></section>' },
  { id: 'divider-deco-diamond-line', kind: 'divider', category: 'divider-decoration',
    name: '菱形横线', keywords: ['菱形', '横线'],
    thumbnail: '<div style="display:flex;align-items:center;justify-content:center;gap:8px;"><div style="flex:1;border-top:1px solid #ddd;"></div><div style="color:#999;">◆</div><div style="flex:1;border-top:1px solid #ddd;"></div></div>',
    html: '<section style="display:flex;align-items:center;justify-content:center;margin:2em 0;"><div style="flex:1;border-top:1px solid #e5e7eb;"></div><section style="padding:0 16px;color:#9ca3af;font-size:10px;">◆</section><div style="flex:1;border-top:1px solid #e5e7eb;"></div></section>' },
  { id: 'divider-deco-heart-line', kind: 'divider', category: 'divider-decoration',
    name: '爱心横线', keywords: ['爱心', '横线', '可爱'],
    thumbnail: '<div style="display:flex;align-items:center;justify-content:center;gap:8px;"><div style="flex:1;border-top:1px solid #fca5a5;"></div><div style="color:#ef4444;">♥</div><div style="flex:1;border-top:1px solid #fca5a5;"></div></div>',
    html: '<section style="display:flex;align-items:center;justify-content:center;margin:2em 0;"><div style="flex:1;border-top:1px solid #fecaca;"></div><section style="padding:0 16px;color:#ef4444;font-size:14px;">♥</section><div style="flex:1;border-top:1px solid #fecaca;"></div></section>' },
  { id: 'divider-deco-thick-dots', kind: 'divider', category: 'divider-decoration',
    name: '大圆点', keywords: ['圆点', '大'],
    thumbnail: '<div style="text-align:center;"><span style="display:inline-block;width:8px;height:8px;background:#6b7280;border-radius:50%;margin:0 4px;"></span><span style="display:inline-block;width:8px;height:8px;background:#6b7280;border-radius:50%;margin:0 4px;"></span><span style="display:inline-block;width:8px;height:8px;background:#6b7280;border-radius:50%;margin:0 4px;"></span></div>',
    html: '<section style="text-align:center;margin:2em 0;"><span style="display:inline-block;width:10px;height:10px;background:#9ca3af;border-radius:50%;margin:0 6px;"></span><span style="display:inline-block;width:10px;height:10px;background:#9ca3af;border-radius:50%;margin:0 6px;"></span><span style="display:inline-block;width:10px;height:10px;background:#9ca3af;border-radius:50%;margin:0 6px;"></span></section>' },
  { id: 'divider-deco-colored-dots', kind: 'divider', category: 'divider-decoration',
    name: '彩色圆点', keywords: ['彩色', '圆点', '活泼'],
    thumbnail: '<div style="text-align:center;"><span style="display:inline-block;width:6px;height:6px;background:#3b82f6;border-radius:50%;margin:0 3px;"></span><span style="display:inline-block;width:6px;height:6px;background:#ef4444;border-radius:50%;margin:0 3px;"></span><span style="display:inline-block;width:6px;height:6px;background:#22c55e;border-radius:50%;margin:0 3px;"></span></div>',
    html: '<section style="text-align:center;margin:2em 0;"><span style="display:inline-block;width:8px;height:8px;background:#3b82f6;border-radius:50%;margin:0 5px;"></span><span style="display:inline-block;width:8px;height:8px;background:#ec4899;border-radius:50%;margin:0 5px;"></span><span style="display:inline-block;width:8px;height:8px;background:#f59e0b;border-radius:50%;margin:0 5px;"></span><span style="display:inline-block;width:8px;height:8px;background:#22c55e;border-radius:50%;margin:0 5px;"></span><span style="display:inline-block;width:8px;height:8px;background:#8b5cf6;border-radius:50%;margin:0 5px;"></span></section>' },
  { id: 'divider-deco-fade-line', kind: 'divider', category: 'divider-decoration',
    name: '淡入淡出线', keywords: ['淡入', '淡出', '优雅'],
    thumbnail: '<div style="height:1px;background:linear-gradient(to right,transparent,#bbb,transparent);"></div>',
    html: '<section style="margin:2em 0;"><div style="height:1px;background:linear-gradient(to right,transparent,#d1d5db 20%,#d1d5db 80%,transparent);"></div></section>' },
  { id: 'divider-deco-shadow-line', kind: 'divider', category: 'divider-decoration',
    name: '阴影线', keywords: ['阴影', '立体'],
    thumbnail: '<div style="height:2px;background:#e5e7eb;box-shadow:0 1px 2px rgba(0,0,0,0.1);"></div>',
    html: '<section style="margin:2em 0;"><div style="height:2px;background:#e5e7eb;box-shadow:0 1px 3px rgba(0,0,0,0.1);border-radius:1px;"></div></section>' },
  { id: 'divider-deco-triple-line', kind: 'divider', category: 'divider-decoration',
    name: '三线组合', keywords: ['三线', '组合'],
    thumbnail: '<div><div style="border-top:1px solid #ccc;"></div><div style="border-top:3px solid #999;margin:3px 0;"></div><div style="border-top:1px solid #ccc;"></div></div>',
    html: '<section style="margin:2em 0;"><div style="border-top:1px solid #d1d5db;"></div><div style="border-top:3px solid #9ca3af;margin:4px 0;"></div><div style="border-top:1px solid #d1d5db;"></div></section>' },
  { id: 'divider-deco-bracket', kind: 'divider', category: 'divider-decoration',
    name: '方括号', keywords: ['方括号', '括号'],
    thumbnail: '<div style="text-align:center;color:#999;font-size:16px;">[ ··· ]</div>',
    html: '<section style="text-align:center;color:#9ca3af;font-size:16px;letter-spacing:0.3em;margin:2em 0;line-height:1;">[ · · · ]</section>' },
  { id: 'divider-deco-tilde', kind: 'divider', category: 'divider-decoration',
    name: '波浪号', keywords: ['波浪号', '分隔'],
    thumbnail: '<div style="text-align:center;color:#999;">~ ~ ~</div>',
    html: '<section style="text-align:center;color:#9ca3af;font-size:16px;letter-spacing:0.4em;margin:2em 0;line-height:1;">~ ~ ~ ~ ~ ~ ~</section>' },
];
