import type { Material } from '../../types';

export const GRADIENT_DIVIDERS: Material[] = [
  { id: 'divider-gradient-lr', kind: 'divider', category: 'divider-gradient',
    name: '左右渐变', keywords: ['渐变', '左右'],
    thumbnail: '<div style="height:2px;background:linear-gradient(to right,transparent,#999,transparent);"></div>',
    html: '<hr style="border:0;height:2px;background:linear-gradient(to right,transparent,#9ca3af 50%,transparent);margin:2em 0;" />' },
  { id: 'divider-gradient-center', kind: 'divider', category: 'divider-gradient',
    name: '中心渐变', keywords: ['中心', '渐变'],
    thumbnail: '<div style="height:2px;background:radial-gradient(ellipse at center,#999,transparent 70%);"></div>',
    html: '<hr style="border:0;height:2px;background:radial-gradient(ellipse at center,#6b7280,transparent 70%);margin:2em 0;" />' },
  { id: 'divider-gradient-dual', kind: 'divider', category: 'divider-gradient',
    name: '双色渐变', keywords: ['双色', '蓝紫'],
    thumbnail: '<div style="height:2px;background:linear-gradient(to right,#3b82f6,#a855f7);"></div>',
    html: '<hr style="border:0;height:2px;background:linear-gradient(to right,#3b82f6,#a855f7);margin:2em 0;" />' },
  { id: 'divider-gradient-triple', kind: 'divider', category: 'divider-gradient',
    name: '三色渐变', keywords: ['三色', '彩虹'],
    thumbnail: '<div style="height:2px;background:linear-gradient(to right,#f59e0b,#ef4444,#8b5cf6);"></div>',
    html: '<hr style="border:0;height:2px;background:linear-gradient(to right,#f59e0b,#ef4444,#8b5cf6);margin:2em 0;" />' },
  // ── 新增渐变 ──
  { id: 'divider-gradient-sunset', kind: 'divider', category: 'divider-gradient',
    name: '日落', keywords: ['日落', '暖色', '橙红'],
    thumbnail: '<div style="height:3px;background:linear-gradient(to right,#f97316,#ef4444,#ec4899);"></div>',
    html: '<hr style="border:0;height:3px;background:linear-gradient(to right,#f97316,#ef4444,#ec4899);margin:2em 0;" />' },
  { id: 'divider-gradient-ocean', kind: 'divider', category: 'divider-gradient',
    name: '海洋', keywords: ['海洋', '蓝色', '青色'],
    thumbnail: '<div style="height:3px;background:linear-gradient(to right,#06b6d4,#3b82f6,#6366f1);"></div>',
    html: '<hr style="border:0;height:3px;background:linear-gradient(to right,#06b6d4,#3b82f6,#6366f1);margin:2em 0;" />' },
  { id: 'divider-gradient-forest', kind: 'divider', category: 'divider-gradient',
    name: '森林', keywords: ['森林', '绿色', '自然'],
    thumbnail: '<div style="height:3px;background:linear-gradient(to right,#22c55e,#16a34a,#15803d);"></div>',
    html: '<hr style="border:0;height:3px;background:linear-gradient(to right,#86efac,#22c55e,#15803d);margin:2em 0;" />' },
  { id: 'divider-gradient-gold', kind: 'divider', category: 'divider-gradient',
    name: '金色', keywords: ['金色', '奢华', '高端'],
    thumbnail: '<div style="height:3px;background:linear-gradient(to right,#f59e0b,#fbbf24,#f59e0b);"></div>',
    html: '<hr style="border:0;height:3px;background:linear-gradient(to right,#d97706,#fbbf24,#f59e0b,#d97706);margin:2em 0;" />' },
  { id: 'divider-gradient-pink', kind: 'divider', category: 'divider-gradient',
    name: '樱花粉', keywords: ['粉色', '樱花', '可爱'],
    thumbnail: '<div style="height:3px;background:linear-gradient(to right,#f9a8d4,#ec4899,#f9a8d4);"></div>',
    html: '<hr style="border:0;height:3px;background:linear-gradient(to right,transparent,#f9a8d4,#ec4899,#f9a8d4,transparent);margin:2em 0;" />' },
  { id: 'divider-gradient-thick-blue', kind: 'divider', category: 'divider-gradient',
    name: '粗蓝渐变', keywords: ['粗线', '蓝色', '醒目'],
    thumbnail: '<div style="height:4px;background:linear-gradient(to right,#3b82f6,#60a5fa);border-radius:2px;"></div>',
    html: '<hr style="border:0;height:4px;background:linear-gradient(to right,#3b82f6,#60a5fa,#3b82f6);border-radius:2px;margin:2em 0;" />' },
  { id: 'divider-gradient-thick-pink', kind: 'divider', category: 'divider-gradient',
    name: '粗粉渐变', keywords: ['粗线', '粉色'],
    thumbnail: '<div style="height:4px;background:linear-gradient(to right,#ec4899,#f472b6);border-radius:2px;"></div>',
    html: '<hr style="border:0;height:4px;background:linear-gradient(to right,#ec4899,#f472b6,#ec4899);border-radius:2px;margin:2em 0;" />' },
  { id: 'divider-gradient-aurora', kind: 'divider', category: 'divider-gradient',
    name: '极光', keywords: ['极光', '梦幻', '彩虹'],
    thumbnail: '<div style="height:3px;background:linear-gradient(to right,#22d3ee,#a78bfa,#f472b6,#fb923c);"></div>',
    html: '<hr style="border:0;height:3px;background:linear-gradient(to right,#22d3ee,#a78bfa,#f472b6,#fb923c);margin:2em 0;" />' },
];
