import type { Material } from '../../types';

const patternBase = (chars: string, color: string, fontSize: string) =>
  `<section style="text-align:center;color:${color};font-size:${fontSize};letter-spacing:0.5em;margin:2em 0;line-height:1;">${chars}</section>`;

export const PATTERN_DIVIDERS: Material[] = [
  { id: 'divider-pattern-asterisk', kind: 'divider', category: 'divider-pattern',
    name: '星号', keywords: ['星号', '星星'],
    thumbnail: '<div style="text-align:center;color:#999;">✱ ✱ ✱</div>',
    html: patternBase('✱ ✱ ✱', '#9ca3af', '14px') },
  { id: 'divider-pattern-spade', kind: 'divider', category: 'divider-pattern',
    name: '黑桃', keywords: ['黑桃'],
    thumbnail: '<div style="text-align:center;color:#999;">❖</div>',
    html: patternBase('❖ ❖ ❖', '#6b7280', '14px') },
  { id: 'divider-pattern-triangle', kind: 'divider', category: 'divider-pattern',
    name: '三角', keywords: ['三角'],
    thumbnail: '<div style="text-align:center;color:#999;">▲ ▲ ▲</div>',
    html: patternBase('▲ ▲ ▲', '#9ca3af', '12px') },
  { id: 'divider-pattern-dots', kind: 'divider', category: 'divider-pattern',
    name: '圆点', keywords: ['圆点', '点'],
    thumbnail: '<div style="text-align:center;color:#999;">● ● ●</div>',
    html: patternBase('● ● ●', '#9ca3af', '8px') },
  { id: 'divider-pattern-flower', kind: 'divider', category: 'divider-pattern',
    name: '花朵', keywords: ['花', '花朵'],
    thumbnail: '<div style="text-align:center;color:#999;">✿</div>',
    html: patternBase('✿ ✿ ✿', '#d97706', '14px') },
  { id: 'divider-pattern-diamond', kind: 'divider', category: 'divider-pattern',
    name: '菱形', keywords: ['菱形'],
    thumbnail: '<div style="text-align:center;color:#999;">◆</div>',
    html: patternBase('◆ ◆ ◆', '#6b7280', '12px') },
  // ── 新增图案 ──
  { id: 'divider-pattern-music', kind: 'divider', category: 'divider-pattern',
    name: '音符', keywords: ['音符', '音乐'],
    thumbnail: '<div style="text-align:center;color:#999;">♪ ♫ ♪</div>',
    html: patternBase('♪ ♫ ♪ ♫ ♪', '#9ca3af', '14px') },
  { id: 'divider-pattern-heart', kind: 'divider', category: 'divider-pattern',
    name: '爱心', keywords: ['爱心', '心形'],
    thumbnail: '<div style="text-align:center;color:#f87171;">♥ ♥ ♥</div>',
    html: patternBase('♥ ♥ ♥ ♥ ♥', '#f87171', '12px') },
  { id: 'divider-pattern-snow', kind: 'divider', category: 'divider-pattern',
    name: '雪花', keywords: ['雪花', '冬天'],
    thumbnail: '<div style="text-align:center;color:#93c5fd;">❄ ❄ ❄</div>',
    html: patternBase('❄ ❄ ❄ ❄ ❄', '#93c5fd', '14px') },
  { id: 'divider-pattern-clover', kind: 'divider', category: 'divider-pattern',
    name: '四叶草', keywords: ['四叶草', '幸运'],
    thumbnail: '<div style="text-align:center;color:#4ade80;">☘ ☘ ☘</div>',
    html: patternBase('☘ ☘ ☘ ☘ ☘', '#4ade80', '14px') },
  { id: 'divider-pattern-crown', kind: 'divider', category: 'divider-pattern',
    name: '皇冠', keywords: ['皇冠', '尊贵'],
    thumbnail: '<div style="text-align:center;color:#fbbf24;">♛ ♛ ♛</div>',
    html: patternBase('♛ ♛ ♛ ♛ ♛', '#fbbf24', '14px') },
  { id: 'divider-pattern-arrow', kind: 'divider', category: 'divider-pattern',
    name: '箭头', keywords: ['箭头', '指向'],
    thumbnail: '<div style="text-align:center;color:#999;">→ → →</div>',
    html: patternBase('▻ ▻ ▻ ▻ ▻ ▻ ▻', '#9ca3af', '10px') },
  { id: 'divider-pattern-wave2', kind: 'divider', category: 'divider-pattern',
    name: '双波浪', keywords: ['波浪', '双线'],
    thumbnail: '<div style="text-align:center;color:#999;">≋ ≋ ≋</div>',
    html: patternBase('≋ ≋ ≋ ≋ ≋ ≋ ≋ ≋ ≋', '#9ca3af', '14px') },
  { id: 'divider-pattern-star-face', kind: 'divider', category: 'divider-pattern',
    name: '笑脸', keywords: ['笑脸', '表情'],
    thumbnail: '<div style="text-align:center;color:#fbbf24;">☆ ★ ☆</div>',
    html: patternBase('★ ☆ ★ ☆ ★', '#fbbf24', '12px') },
  { id: 'divider-pattern-dash', kind: 'divider', category: 'divider-pattern',
    name: '短划线', keywords: ['短划', '虚线'],
    thumbnail: '<div style="text-align:center;color:#999;">- - -</div>',
    html: patternBase('— — — — — — — — —', '#9ca3af', '10px') },
  { id: 'divider-pattern-dot-dash', kind: 'divider', category: 'divider-pattern',
    name: '点划线', keywords: ['点划', '交替'],
    thumbnail: '<div style="text-align:center;color:#999;">·—·—·</div>',
    html: patternBase('· — · — · — · — ·', '#9ca3af', '10px') },
];
